version: '3.8'

services:
  server:
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000

  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      POSTGRES_DB: example
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
    expose: 
      - "5432"
    secrets: 
      - db-password
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes: 
  postgres_data:

secrets:
  db-password:
    file: ./db/password.txt

